# Generated by Django 5.0.1 on 2024-01-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('languages', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('imgFramework', models.ImageField(blank=True, null=True, upload_to='imgFramework')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('creador', models.CharField(max_length=15)),
                ('version', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
