# Generated by Django 5.0.1 on 2024-01-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='imgFramework',
            field=models.ImageField(blank=True, null=True, upload_to='framework'),
        ),
    ]
