# Generated by Django 5.0.1 on 2024-01-12 15:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto4', '0003_alter_language_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='language',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
